<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Trantor-LP260" failures="1" tests="1" name="Default test" time="6.489" errors="0" timestamp="2024-08-19T16:03:27 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.603">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this servicee] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this servicee] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PageFactory.loginPageFactory.loginErrorMsg(loginPageFactory.java:94)
at StepDefinitions.loginStepDefinitions.should_show_the_error_message(loginStepDefinitions.java:62)
at âœ½.Should show the error message(file:///C:/Users/somendra.chauhan/eclipse-workspace/BDDProject/src/test/resources/FeatureFile/login.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
