<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-11T20:49:34 IST" name="Default suite" finished-at="2024-08-11T20:49:46 IST" duration-ms="12553">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.loginTestRunner@2aceadd4]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-08-11T20:49:34 IST" name="Default test" finished-at="2024-08-11T20:49:46 IST" duration-ms="12553">
      <class name="TestRunner.loginTestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:TestRunner.loginTestRunner@2aceadd4]" started-at="2024-08-11T20:49:34 IST" name="setUpClass" finished-at="2024-08-11T20:49:34 IST" duration-ms="763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4228bf58]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner.loginTestRunner@2aceadd4]" started-at="2024-08-11T20:49:34 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-08-11T20:49:46 IST" duration-ms="11687" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Check Login with invalid credentails"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Scenario"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Username and password do not match any user in this servicee] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this servicee] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PageFactory.loginPageFactory.loginErrorMsg(loginPageFactory.java:94)
at StepDefinitions.loginStepDefinitions.should_show_the_error_message(loginStepDefinitions.java:62)
at âœ½.Should show the error message(file:///C:/Users/somendra.chauhan/eclipse-workspace/BDDProject/src/test/resources/FeatureFile/login.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunner.loginTestRunner@2aceadd4]" started-at="2024-08-11T20:49:46 IST" name="tearDownClass" finished-at="2024-08-11T20:49:46 IST" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner.loginTestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
